### ISSUE TITLE
Can you support other cpu ABIS?

### ISSUE THREAD

**Issue by hwangjr** [AnyMarvel/ManPinAPP#3]
I found the source cpu ABIS only support `arm64-v8a`, can you support other cpu ABIS like `x86`, `x86_64`, `armeabi`, `armeabi-v7a` ?

OR

Can you provide the source code about `libfilter_native.so`, `libfilterframework_jni.so`

**Comment by AnyMarvel** [comment]
Sorry, this feature is no longer maintained due to labor costs.
