### ISSUE TITLE
没有找到So动态加载相关的代码

### ISSUE THREAD

**Issue by CarryHekangkai** [AnyMarvel/ManPinAPP#7]
项目中未找到nativeLibraryDirectories、nativeLibraryPathElements和LoadLibraryUtil相关的关于So库动态加载的代码，请问是否已经移除该功能？为什么移除该功能？

**Comment by AnyMarvel** [comment]
代码已删除，可以基于git记录恢复

**Comment by pengMaster** [comment]
@AnyMarvel 为啥删了？不稳定么？

**Comment by stewForAni** [comment]
> 代码已删除，可以基于git记录恢复

请问为什么删了？
